# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hdqt5ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.installPlugin3Btn = QtWidgets.QPushButton(self.centralwidget)
        self.installPlugin3Btn.setGeometry(QtCore.QRect(90, 20, 75, 23))
        self.installPlugin3Btn.setObjectName("installPlugin3Btn")
        self.LoginInitFun = QtWidgets.QPushButton(self.centralwidget)
        self.LoginInitFun.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.LoginInitFun.setObjectName("LoginInitFun")
        self.startCaptureBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startCaptureBtn.setGeometry(QtCore.QRect(170, 20, 75, 23))
        self.startCaptureBtn.setObjectName("startCaptureBtn")
        self.closeCaptureBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeCaptureBtn.setGeometry(QtCore.QRect(250, 20, 75, 23))
        self.closeCaptureBtn.setObjectName("closeCaptureBtn")
        self.bindBtn = QtWidgets.QPushButton(self.centralwidget)
        self.bindBtn.setGeometry(QtCore.QRect(340, 20, 75, 23))
        self.bindBtn.setObjectName("bindBtn")
        self.pauseBindBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBindBtn.setGeometry(QtCore.QRect(430, 20, 75, 23))
        self.pauseBindBtn.setObjectName("pauseBindBtn")
        self.recoverBindBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recoverBindBtn.setGeometry(QtCore.QRect(520, 20, 75, 23))
        self.recoverBindBtn.setObjectName("recoverBindBtn")
        self.unbindBtn = QtWidgets.QPushButton(self.centralwidget)
        self.unbindBtn.setGeometry(QtCore.QRect(610, 20, 75, 23))
        self.unbindBtn.setObjectName("unbindBtn")
        self.findPicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.findPicBtn.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.findPicBtn.setObjectName("findPicBtn")
        self.findPicTemBtn = QtWidgets.QPushButton(self.centralwidget)
        self.findPicTemBtn.setGeometry(QtCore.QRect(90, 50, 151, 23))
        self.findPicTemBtn.setObjectName("findPicTemBtn")
        self.findWordBtn = QtWidgets.QPushButton(self.centralwidget)
        self.findWordBtn.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.findWordBtn.setObjectName("findWordBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HD内存图色插件 基础课程 Python  882724064"))
        self.installPlugin3Btn.setText(_translate("MainWindow", "安装插件3"))
        self.LoginInitFun.setText(_translate("MainWindow", "登录初始化"))
        self.startCaptureBtn.setText(_translate("MainWindow", "开启截图Ex"))
        self.closeCaptureBtn.setText(_translate("MainWindow", "关闭截图Ex"))
        self.bindBtn.setText(_translate("MainWindow", "绑定后台"))
        self.pauseBindBtn.setText(_translate("MainWindow", "暂停绑定"))
        self.recoverBindBtn.setText(_translate("MainWindow", "恢复绑定"))
        self.unbindBtn.setText(_translate("MainWindow", "解绑后台"))
        self.findPicBtn.setText(_translate("MainWindow", "识图Ex(静)"))
        self.findPicTemBtn.setText(_translate("MainWindow", "智能识图Tem(动/静)"))
        self.findWordBtn.setText(_translate("MainWindow", "AutoEx识字"))
