# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hdqtcontrolui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 438)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(10, 310, 75, 23))
        self.startBtn.setObjectName("startBtn")
        self.stopBTn = QtWidgets.QPushButton(self.centralwidget)
        self.stopBTn.setGeometry(QtCore.QRect(100, 310, 75, 23))
        self.stopBTn.setObjectName("stopBTn")
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBtn.setGeometry(QtCore.QRect(190, 310, 75, 23))
        self.pauseBtn.setObjectName("pauseBtn")
        self.recoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.recoverBtn.setGeometry(QtCore.QRect(280, 310, 75, 23))
        self.recoverBtn.setObjectName("recoverBtn")
        self.restartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.restartBtn.setGeometry(QtCore.QRect(370, 310, 75, 23))
        self.restartBtn.setObjectName("restartBtn")
        self.allStartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.allStartBtn.setGeometry(QtCore.QRect(10, 340, 75, 23))
        self.allStartBtn.setObjectName("allStartBtn")
        self.allStopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.allStopBtn.setGeometry(QtCore.QRect(100, 340, 75, 23))
        self.allStopBtn.setObjectName("allStopBtn")
        self.allPauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.allPauseBtn.setGeometry(QtCore.QRect(190, 340, 75, 23))
        self.allPauseBtn.setObjectName("allPauseBtn")
        self.allRecoverBtn = QtWidgets.QPushButton(self.centralwidget)
        self.allRecoverBtn.setGeometry(QtCore.QRect(280, 340, 75, 23))
        self.allRecoverBtn.setObjectName("allRecoverBtn")
        self.logEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.logEdit.setGeometry(QtCore.QRect(720, 310, 381, 101))
        self.logEdit.setObjectName("logEdit")
        self.accountTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.accountTableWidget.setGeometry(QtCore.QRect(10, 10, 1091, 291))
        self.accountTableWidget.setObjectName("accountTableWidget")
        self.accountTableWidget.setColumnCount(0)
        self.accountTableWidget.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 370, 341, 20))
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python QT5 HD内存图色插件 多线程框架 www.hdgdk.com 882724064  "))
        self.startBtn.setText(_translate("MainWindow", "单个开启"))
        self.stopBTn.setText(_translate("MainWindow", "单个结束"))
        self.pauseBtn.setText(_translate("MainWindow", "单个暂停"))
        self.recoverBtn.setText(_translate("MainWindow", "单个恢复"))
        self.restartBtn.setText(_translate("MainWindow", "单个重启"))
        self.allStartBtn.setText(_translate("MainWindow", "全部开启"))
        self.allStopBtn.setText(_translate("MainWindow", "全部停止"))
        self.allPauseBtn.setText(_translate("MainWindow", "全部暂停"))
        self.allRecoverBtn.setText(_translate("MainWindow", "全部恢复"))
        self.lineEdit.setToolTip(_translate("MainWindow", "请输入卡密..."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入卡密..."))
